ktor:
  application:
    modules:
      - ru.hse.store.ApplicationKt.module
  deployment:
    port: 8082
postgres:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/hw}
  username: ${DB_USERNAME:user}
  password: ${DB_PASSWORD:pass}
  driver: org.postgresql.Driver
  maximumPoolSize: 5
  autoCommit: false
  transactionIsolation: TRANSACTION_REPEATABLE_READ