ktor:
  application:
    modules:
      - ru.hse.orders.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/orders_db}
  username: ${DB_USERNAME:admin}
  password: ${DB_PASSWORD:password}
  driver: org.postgresql.Driver
  maximumPoolSize: 5

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    paymentRequest: payment-request
    paymentStatus: payment-status

