ktor:
  application:
    modules:
      - ru.hse.apphost.ApplicationKt.module
  deployment:
    port: 8080
rpc:
  analyse:
    url: ${ANALYSE_URL:ws://localhost:8081/services}
  store:
    url: ${STORE_URL:ws://localhost:8082/services}