ktor:
  application:
    modules:
      - ru.hse.apphost.ApplicationKt.module
  deployment:
    port: 8080

services:
  orders:
    url: ${ORDERS_SERVICE_URL:http://orders-service:8080}
  payments:
    url: ${PAYMENTS_SERVICE_URL:http://payments-service:8081}

